name: Unit Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0

      - name: Install Project Dependencies
        run: |
          npm install
          forge install --no-git --no-commit foundry-rs/forge-std@v1.7.3

      - name: Lint Check
        run: |
          npm run lint:check

      - name: Build
        run: |
          forge build

      - name: Set RPC Env
        run: echo "RPC_BSC=https://bsc-dataseed.bnbchain.org" >> $GITHUB_ENV

      - name: Unit Test
        run: |
          forge test
